blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/noam324/Project-Flashback/security/advisories
    about: Please use the security reporting process for vulnerabilities.
